/***************************************************************************//**
 * @file
 * @brief
 *******************************************************************************
 * # License
 * <b>Copyright 2023 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * SPDX-License-Identifier: Zlib
 *
 * The licensor of this software is Silicon Laboratories Inc.
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 ******************************************************************************/

#ifndef SL_RAIL_UTIL_HADM_GDCOMP_CONFIG_H
#define SL_RAIL_UTIL_HADM_GDCOMP_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define SL_RAIL_UTIL_HADM_GDCOMP_RUNTIME_PA_TABLE_SELECTION 0

#define SL_RAIL_UTIL_HADM_GDCOMP_TABLE_LENGTH 25U

#define SL_RAIL_UTIL_HADM_GDCOMP_RTT_SLOPE_0DBM_PA \
  {                                                \
    97, 98, 95, 98, 97,                            \
    98, 95, 94, 96, 99,                            \
    98, 102, 95, 102, 97,                          \
    96, 97, 99, 95, 91,                            \
    88, 93, 93, 93, 93,                            \
  }

#define SL_RAIL_UTIL_HADM_GDCOMP_RTT_OFFSET_0DBM_PA \
  {                                                 \
    -2435, -2766, -2950, -2708, -3329,              \
    -3720, -1268, -1620, -2052, -2549,              \
    -2640, -2776, -2464, -2590, -2516,              \
    -2478, -2884, -2497, -2983, -2726,              \
    -2883, -3091, -3091, -3091, -3091,              \
  }

#define SL_RAIL_UTIL_HADM_GDCOMP_RTT_SLOPE_10DBM_PA \
  {                                                 \
    97, 98, 95, 98, 97,                             \
    98, 95, 94, 96, 99,                             \
    98, 102, 95, 102, 97,                           \
    96, 97, 99, 95, 91,                             \
    88, 93, 93, 93, 93,                             \
  }

#define SL_RAIL_UTIL_HADM_GDCOMP_RTT_OFFSET_10DBM_PA \
  {                                                  \
    -2435, -2766, -2950, -2708, -3329,               \
    -3720, -1268, -1620, -2052, -2549,               \
    -2640, -2776, -2464, -2590, -2516,               \
    -2478, -2884, -2497, -2983, -2726,               \
    -2883, -3091, -3091, -3091, -3091,               \
  }

#define SL_RAIL_UTIL_HADM_GDCOMP_RTT_SLOPE_20DBM_PA \
  {                                                 \
    97, 98, 95, 98, 97,                             \
    98, 95, 94, 96, 99,                             \
    98, 102, 95, 102, 97,                           \
    96, 97, 99, 95, 91,                             \
    88, 93, 93, 93, 93                              \
  }

#define SL_RAIL_UTIL_HADM_GDCOMP_RTT_OFFSET_20DBM_PA \
  {                                                  \
    -2435, -2766, -2950, -2708, -3329,               \
    -3720, -1268, -1620, -2052, -2549,               \
    -2640, -2776, -2464, -2590, -2516,               \
    -2478, -2884, -2497, -2983, -2726,               \
    -2883, -3091, -3091, -3091, -3091,               \
  }

// AUTOGENERATED testRunCalibration.m 20230828_2220_c06eaf7f
#define SL_RAIL_UTIL_HADM_GDCOMP_PBR_0DBM_PA \
  {                                          \
    4, 4, 5, 4, 4,                           \
    4, 4, 5, 4, 4,                           \
    4, 4, 4, 3, 4,                           \
    5, 4, 5, 4, 4,                           \
    2, 3, 3, 1, 1,                           \
  }

// AUTOGENERATED testRunCalibration.m 20230828_2220_c06eaf7f
#define SL_RAIL_UTIL_HADM_GDCOMP_PBR_10DBM_PA \
  {                                           \
    17, 17, 17, 18, 18,                       \
    19, 18, 19, 18, 18,                       \
    19, 18, 17, 18, 18,                       \
    17, 16, 17, 17, 19,                       \
    20, 19, 19, 19, 19,                       \
  }

// AUTOGENERATED testRunCalibration.m 20230908_2159_9791097d
#define SL_RAIL_UTIL_HADM_GDCOMP_PBR_20DBM_PA \
  {                                           \
    33, 33, 31, 31, 30,                       \
    32, 32, 31, 30, 27,                       \
    28, 28, 27, 27, 28,                       \
    26, 27, 26, 27, 30,                       \
    30, 30, 30, 31, 31,                       \
  }

#ifdef __cplusplus
}
#endif

#endif // SL_RAIL_UTIL_HADM_GDCOMP_CONFIG_H
