
# -*- coding: utf-8 -*-

__all__ = [ 'RM_Peripheral_MODEM_NS' ]

from . static import Base_RM_Peripheral
from . MODEM_NS_register import *

class RM_Peripheral_MODEM_NS(Base_RM_Peripheral):
    def __init__(self, rmio, label):
        self.__dict__['zz_frozen'] = False
        super(RM_Peripheral_MODEM_NS, self).__init__(rmio, label,
            0xB8014000, 'MODEM_NS',
            u"",
            [])
        self.IPVERSION = RM_Register_MODEM_NS_IPVERSION(self.zz_rmio, self.zz_label)
        self.zz_rdict['IPVERSION'] = self.IPVERSION
        self.EN = RM_Register_MODEM_NS_EN(self.zz_rmio, self.zz_label)
        self.zz_rdict['EN'] = self.EN
        self.IF = RM_Register_MODEM_NS_IF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IF'] = self.IF
        self.IEN = RM_Register_MODEM_NS_IEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['IEN'] = self.IEN
        self.SEQIF = RM_Register_MODEM_NS_SEQIF(self.zz_rmio, self.zz_label)
        self.zz_rdict['SEQIF'] = self.SEQIF
        self.SEQIEN = RM_Register_MODEM_NS_SEQIEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['SEQIEN'] = self.SEQIEN
        self.STATUS = RM_Register_MODEM_NS_STATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS'] = self.STATUS
        self.STATUS2 = RM_Register_MODEM_NS_STATUS2(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS2'] = self.STATUS2
        self.STATUS3 = RM_Register_MODEM_NS_STATUS3(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS3'] = self.STATUS3
        self.STATUS4 = RM_Register_MODEM_NS_STATUS4(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS4'] = self.STATUS4
        self.STATUS5 = RM_Register_MODEM_NS_STATUS5(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS5'] = self.STATUS5
        self.STATUS6 = RM_Register_MODEM_NS_STATUS6(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS6'] = self.STATUS6
        self.STATUS7 = RM_Register_MODEM_NS_STATUS7(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS7'] = self.STATUS7
        self.TIMDETSTATUS = RM_Register_MODEM_NS_TIMDETSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['TIMDETSTATUS'] = self.TIMDETSTATUS
        self.FSMSTATUS = RM_Register_MODEM_NS_FSMSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['FSMSTATUS'] = self.FSMSTATUS
        self.FREQOFFEST = RM_Register_MODEM_NS_FREQOFFEST(self.zz_rmio, self.zz_label)
        self.zz_rdict['FREQOFFEST'] = self.FREQOFFEST
        self.AFCADJRX = RM_Register_MODEM_NS_AFCADJRX(self.zz_rmio, self.zz_label)
        self.zz_rdict['AFCADJRX'] = self.AFCADJRX
        self.AFCADJTX = RM_Register_MODEM_NS_AFCADJTX(self.zz_rmio, self.zz_label)
        self.zz_rdict['AFCADJTX'] = self.AFCADJTX
        self.MIXCTRL = RM_Register_MODEM_NS_MIXCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['MIXCTRL'] = self.MIXCTRL
        self.CTRL0 = RM_Register_MODEM_NS_CTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL0'] = self.CTRL0
        self.CTRL1 = RM_Register_MODEM_NS_CTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL1'] = self.CTRL1
        self.CTRL2 = RM_Register_MODEM_NS_CTRL2(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL2'] = self.CTRL2
        self.CTRL3 = RM_Register_MODEM_NS_CTRL3(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL3'] = self.CTRL3
        self.CTRL4 = RM_Register_MODEM_NS_CTRL4(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL4'] = self.CTRL4
        self.CTRL5 = RM_Register_MODEM_NS_CTRL5(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL5'] = self.CTRL5
        self.CTRL6 = RM_Register_MODEM_NS_CTRL6(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL6'] = self.CTRL6
        self.TXBR = RM_Register_MODEM_NS_TXBR(self.zz_rmio, self.zz_label)
        self.zz_rdict['TXBR'] = self.TXBR
        self.RXBR = RM_Register_MODEM_NS_RXBR(self.zz_rmio, self.zz_label)
        self.zz_rdict['RXBR'] = self.RXBR
        self.CF = RM_Register_MODEM_NS_CF(self.zz_rmio, self.zz_label)
        self.zz_rdict['CF'] = self.CF
        self.PRE = RM_Register_MODEM_NS_PRE(self.zz_rmio, self.zz_label)
        self.zz_rdict['PRE'] = self.PRE
        self.TIMING = RM_Register_MODEM_NS_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['TIMING'] = self.TIMING
        self.DSSS0 = RM_Register_MODEM_NS_DSSS0(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSSS0'] = self.DSSS0
        self.MODINDEX = RM_Register_MODEM_NS_MODINDEX(self.zz_rmio, self.zz_label)
        self.zz_rdict['MODINDEX'] = self.MODINDEX
        self.AFC = RM_Register_MODEM_NS_AFC(self.zz_rmio, self.zz_label)
        self.zz_rdict['AFC'] = self.AFC
        self.AFCADJLIM = RM_Register_MODEM_NS_AFCADJLIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['AFCADJLIM'] = self.AFCADJLIM
        self.SHAPING0 = RM_Register_MODEM_NS_SHAPING0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING0'] = self.SHAPING0
        self.SHAPING1 = RM_Register_MODEM_NS_SHAPING1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING1'] = self.SHAPING1
        self.SHAPING2 = RM_Register_MODEM_NS_SHAPING2(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING2'] = self.SHAPING2
        self.SHAPING3 = RM_Register_MODEM_NS_SHAPING3(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING3'] = self.SHAPING3
        self.SHAPING4 = RM_Register_MODEM_NS_SHAPING4(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING4'] = self.SHAPING4
        self.SHAPING5 = RM_Register_MODEM_NS_SHAPING5(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING5'] = self.SHAPING5
        self.SHAPING6 = RM_Register_MODEM_NS_SHAPING6(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING6'] = self.SHAPING6
        self.SHAPING7 = RM_Register_MODEM_NS_SHAPING7(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING7'] = self.SHAPING7
        self.SHAPING8 = RM_Register_MODEM_NS_SHAPING8(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING8'] = self.SHAPING8
        self.SHAPING9 = RM_Register_MODEM_NS_SHAPING9(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING9'] = self.SHAPING9
        self.SHAPING10 = RM_Register_MODEM_NS_SHAPING10(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING10'] = self.SHAPING10
        self.SHAPING11 = RM_Register_MODEM_NS_SHAPING11(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING11'] = self.SHAPING11
        self.SHAPING12 = RM_Register_MODEM_NS_SHAPING12(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING12'] = self.SHAPING12
        self.SHAPING13 = RM_Register_MODEM_NS_SHAPING13(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING13'] = self.SHAPING13
        self.SHAPING14 = RM_Register_MODEM_NS_SHAPING14(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING14'] = self.SHAPING14
        self.SHAPING15 = RM_Register_MODEM_NS_SHAPING15(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING15'] = self.SHAPING15
        self.RAMPCTRL = RM_Register_MODEM_NS_RAMPCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['RAMPCTRL'] = self.RAMPCTRL
        self.RAMPLEV = RM_Register_MODEM_NS_RAMPLEV(self.zz_rmio, self.zz_label)
        self.zz_rdict['RAMPLEV'] = self.RAMPLEV
        self.ANARAMPCTRL = RM_Register_MODEM_NS_ANARAMPCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANARAMPCTRL'] = self.ANARAMPCTRL
        self.DCCOMP = RM_Register_MODEM_NS_DCCOMP(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCCOMP'] = self.DCCOMP
        self.DCCOMPFILTINIT = RM_Register_MODEM_NS_DCCOMPFILTINIT(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCCOMPFILTINIT'] = self.DCCOMPFILTINIT
        self.DCESTI = RM_Register_MODEM_NS_DCESTI(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCESTI'] = self.DCESTI
        self.SRCCHF = RM_Register_MODEM_NS_SRCCHF(self.zz_rmio, self.zz_label)
        self.zz_rdict['SRCCHF'] = self.SRCCHF
        self.INTAFC = RM_Register_MODEM_NS_INTAFC(self.zz_rmio, self.zz_label)
        self.zz_rdict['INTAFC'] = self.INTAFC
        self.DSATHD0 = RM_Register_MODEM_NS_DSATHD0(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD0'] = self.DSATHD0
        self.DSATHD1 = RM_Register_MODEM_NS_DSATHD1(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD1'] = self.DSATHD1
        self.DSATHD2 = RM_Register_MODEM_NS_DSATHD2(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD2'] = self.DSATHD2
        self.DSATHD3 = RM_Register_MODEM_NS_DSATHD3(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD3'] = self.DSATHD3
        self.DSATHD4 = RM_Register_MODEM_NS_DSATHD4(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD4'] = self.DSATHD4
        self.DSACTRL = RM_Register_MODEM_NS_DSACTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSACTRL'] = self.DSACTRL
        self.DIGMIXCTRL = RM_Register_MODEM_NS_DIGMIXCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIGMIXCTRL'] = self.DIGMIXCTRL
        self.VITERBIDEMOD = RM_Register_MODEM_NS_VITERBIDEMOD(self.zz_rmio, self.zz_label)
        self.zz_rdict['VITERBIDEMOD'] = self.VITERBIDEMOD
        self.VTCORRCFG0 = RM_Register_MODEM_NS_VTCORRCFG0(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTCORRCFG0'] = self.VTCORRCFG0
        self.VTCORRCFG1 = RM_Register_MODEM_NS_VTCORRCFG1(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTCORRCFG1'] = self.VTCORRCFG1
        self.VTTRACK = RM_Register_MODEM_NS_VTTRACK(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTTRACK'] = self.VTTRACK
        self.VTBLETIMING = RM_Register_MODEM_NS_VTBLETIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTBLETIMING'] = self.VTBLETIMING
        self.BREST = RM_Register_MODEM_NS_BREST(self.zz_rmio, self.zz_label)
        self.zz_rdict['BREST'] = self.BREST
        self.AUTOCG = RM_Register_MODEM_NS_AUTOCG(self.zz_rmio, self.zz_label)
        self.zz_rdict['AUTOCG'] = self.AUTOCG
        self.CGCLKSTOP = RM_Register_MODEM_NS_CGCLKSTOP(self.zz_rmio, self.zz_label)
        self.zz_rdict['CGCLKSTOP'] = self.CGCLKSTOP
        self.POE = RM_Register_MODEM_NS_POE(self.zz_rmio, self.zz_label)
        self.zz_rdict['POE'] = self.POE
        self.DIRECTMODE = RM_Register_MODEM_NS_DIRECTMODE(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIRECTMODE'] = self.DIRECTMODE
        self.LONGRANGE = RM_Register_MODEM_NS_LONGRANGE(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE'] = self.LONGRANGE
        self.LONGRANGE1 = RM_Register_MODEM_NS_LONGRANGE1(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE1'] = self.LONGRANGE1
        self.LONGRANGE2 = RM_Register_MODEM_NS_LONGRANGE2(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE2'] = self.LONGRANGE2
        self.LONGRANGE3 = RM_Register_MODEM_NS_LONGRANGE3(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE3'] = self.LONGRANGE3
        self.LONGRANGE4 = RM_Register_MODEM_NS_LONGRANGE4(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE4'] = self.LONGRANGE4
        self.LONGRANGE5 = RM_Register_MODEM_NS_LONGRANGE5(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE5'] = self.LONGRANGE5
        self.LONGRANGE6 = RM_Register_MODEM_NS_LONGRANGE6(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE6'] = self.LONGRANGE6
        self.LRFRC = RM_Register_MODEM_NS_LRFRC(self.zz_rmio, self.zz_label)
        self.zz_rdict['LRFRC'] = self.LRFRC
        self.COH0 = RM_Register_MODEM_NS_COH0(self.zz_rmio, self.zz_label)
        self.zz_rdict['COH0'] = self.COH0
        self.COH1 = RM_Register_MODEM_NS_COH1(self.zz_rmio, self.zz_label)
        self.zz_rdict['COH1'] = self.COH1
        self.COH2 = RM_Register_MODEM_NS_COH2(self.zz_rmio, self.zz_label)
        self.zz_rdict['COH2'] = self.COH2
        self.COH3 = RM_Register_MODEM_NS_COH3(self.zz_rmio, self.zz_label)
        self.zz_rdict['COH3'] = self.COH3
        self.CMD = RM_Register_MODEM_NS_CMD(self.zz_rmio, self.zz_label)
        self.zz_rdict['CMD'] = self.CMD
        self.SYNCPROPERTIES = RM_Register_MODEM_NS_SYNCPROPERTIES(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNCPROPERTIES'] = self.SYNCPROPERTIES
        self.DIGIGAINCTRL = RM_Register_MODEM_NS_DIGIGAINCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIGIGAINCTRL'] = self.DIGIGAINCTRL
        self.PRSCTRL = RM_Register_MODEM_NS_PRSCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PRSCTRL'] = self.PRSCTRL
        self.PADEBUG = RM_Register_MODEM_NS_PADEBUG(self.zz_rmio, self.zz_label)
        self.zz_rdict['PADEBUG'] = self.PADEBUG
        self.REALTIMCFE = RM_Register_MODEM_NS_REALTIMCFE(self.zz_rmio, self.zz_label)
        self.zz_rdict['REALTIMCFE'] = self.REALTIMCFE
        self.ETSCTRL = RM_Register_MODEM_NS_ETSCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['ETSCTRL'] = self.ETSCTRL
        self.ETSTIM = RM_Register_MODEM_NS_ETSTIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['ETSTIM'] = self.ETSTIM
        self.ANTSWCTRL = RM_Register_MODEM_NS_ANTSWCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTSWCTRL'] = self.ANTSWCTRL
        self.ANTSWCTRL1 = RM_Register_MODEM_NS_ANTSWCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTSWCTRL1'] = self.ANTSWCTRL1
        self.ANTSWSTART = RM_Register_MODEM_NS_ANTSWSTART(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTSWSTART'] = self.ANTSWSTART
        self.ANTSWEND = RM_Register_MODEM_NS_ANTSWEND(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTSWEND'] = self.ANTSWEND
        self.TRECPMPATT = RM_Register_MODEM_NS_TRECPMPATT(self.zz_rmio, self.zz_label)
        self.zz_rdict['TRECPMPATT'] = self.TRECPMPATT
        self.TRECPMDET = RM_Register_MODEM_NS_TRECPMDET(self.zz_rmio, self.zz_label)
        self.zz_rdict['TRECPMDET'] = self.TRECPMDET
        self.TRECSCFG = RM_Register_MODEM_NS_TRECSCFG(self.zz_rmio, self.zz_label)
        self.zz_rdict['TRECSCFG'] = self.TRECSCFG
        self.CFGANTPATT = RM_Register_MODEM_NS_CFGANTPATT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CFGANTPATT'] = self.CFGANTPATT
        self.COCURRMODE = RM_Register_MODEM_NS_COCURRMODE(self.zz_rmio, self.zz_label)
        self.zz_rdict['COCURRMODE'] = self.COCURRMODE
        self.CHFCOE00 = RM_Register_MODEM_NS_CHFCOE00(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE00'] = self.CHFCOE00
        self.CHFCOE01 = RM_Register_MODEM_NS_CHFCOE01(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE01'] = self.CHFCOE01
        self.CHFCOE02 = RM_Register_MODEM_NS_CHFCOE02(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE02'] = self.CHFCOE02
        self.CHFCOE03 = RM_Register_MODEM_NS_CHFCOE03(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE03'] = self.CHFCOE03
        self.CHFCOE04 = RM_Register_MODEM_NS_CHFCOE04(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE04'] = self.CHFCOE04
        self.CHFCOE05 = RM_Register_MODEM_NS_CHFCOE05(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE05'] = self.CHFCOE05
        self.CHFCOE06 = RM_Register_MODEM_NS_CHFCOE06(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE06'] = self.CHFCOE06
        self.CHFCOE10 = RM_Register_MODEM_NS_CHFCOE10(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE10'] = self.CHFCOE10
        self.CHFCOE11 = RM_Register_MODEM_NS_CHFCOE11(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE11'] = self.CHFCOE11
        self.CHFCOE12 = RM_Register_MODEM_NS_CHFCOE12(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE12'] = self.CHFCOE12
        self.CHFCOE13 = RM_Register_MODEM_NS_CHFCOE13(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE13'] = self.CHFCOE13
        self.CHFCOE14 = RM_Register_MODEM_NS_CHFCOE14(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE14'] = self.CHFCOE14
        self.CHFCOE15 = RM_Register_MODEM_NS_CHFCOE15(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE15'] = self.CHFCOE15
        self.CHFCOE16 = RM_Register_MODEM_NS_CHFCOE16(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCOE16'] = self.CHFCOE16
        self.CHFCTRL = RM_Register_MODEM_NS_CHFCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFCTRL'] = self.CHFCTRL
        self.CHFLATENCYCTRL = RM_Register_MODEM_NS_CHFLATENCYCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFLATENCYCTRL'] = self.CHFLATENCYCTRL
        self.FRMSCHTIME = RM_Register_MODEM_NS_FRMSCHTIME(self.zz_rmio, self.zz_label)
        self.zz_rdict['FRMSCHTIME'] = self.FRMSCHTIME
        self.PREFILTCOEFF = RM_Register_MODEM_NS_PREFILTCOEFF(self.zz_rmio, self.zz_label)
        self.zz_rdict['PREFILTCOEFF'] = self.PREFILTCOEFF
        self.RXRESTART = RM_Register_MODEM_NS_RXRESTART(self.zz_rmio, self.zz_label)
        self.zz_rdict['RXRESTART'] = self.RXRESTART
        self.SQ = RM_Register_MODEM_NS_SQ(self.zz_rmio, self.zz_label)
        self.zz_rdict['SQ'] = self.SQ
        self.SQEXT = RM_Register_MODEM_NS_SQEXT(self.zz_rmio, self.zz_label)
        self.zz_rdict['SQEXT'] = self.SQEXT
        self.SQI = RM_Register_MODEM_NS_SQI(self.zz_rmio, self.zz_label)
        self.zz_rdict['SQI'] = self.SQI
        self.ANTDIVCTRL = RM_Register_MODEM_NS_ANTDIVCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTDIVCTRL'] = self.ANTDIVCTRL
        self.ANTDIVFW = RM_Register_MODEM_NS_ANTDIVFW(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTDIVFW'] = self.ANTDIVFW
        self.PHDMODANTDIV = RM_Register_MODEM_NS_PHDMODANTDIV(self.zz_rmio, self.zz_label)
        self.zz_rdict['PHDMODANTDIV'] = self.PHDMODANTDIV
        self.PHANTDECSION = RM_Register_MODEM_NS_PHANTDECSION(self.zz_rmio, self.zz_label)
        self.zz_rdict['PHANTDECSION'] = self.PHANTDECSION
        self.PHDMODCTRL = RM_Register_MODEM_NS_PHDMODCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PHDMODCTRL'] = self.PHDMODCTRL
        self.SICORR = RM_Register_MODEM_NS_SICORR(self.zz_rmio, self.zz_label)
        self.zz_rdict['SICORR'] = self.SICORR
        self.SICTRL0 = RM_Register_MODEM_NS_SICTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SICTRL0'] = self.SICTRL0
        self.SICTRL1 = RM_Register_MODEM_NS_SICTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SICTRL1'] = self.SICTRL1
        self.SISTATUS = RM_Register_MODEM_NS_SISTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['SISTATUS'] = self.SISTATUS
        self.CFGANTPATTEXT = RM_Register_MODEM_NS_CFGANTPATTEXT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CFGANTPATTEXT'] = self.CFGANTPATTEXT
        self.SICTRL2 = RM_Register_MODEM_NS_SICTRL2(self.zz_rmio, self.zz_label)
        self.zz_rdict['SICTRL2'] = self.SICTRL2
        self.CHFSWCTRL = RM_Register_MODEM_NS_CHFSWCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFSWCTRL'] = self.CHFSWCTRL
        self.DUALTIM = RM_Register_MODEM_NS_DUALTIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['DUALTIM'] = self.DUALTIM
        self.DIGMIXCTRL1 = RM_Register_MODEM_NS_DIGMIXCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIGMIXCTRL1'] = self.DIGMIXCTRL1
        self.SRCCHF1 = RM_Register_MODEM_NS_SRCCHF1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SRCCHF1'] = self.SRCCHF1
        self.IRCAL = RM_Register_MODEM_NS_IRCAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['IRCAL'] = self.IRCAL
        self.IRCALCOEF = RM_Register_MODEM_NS_IRCALCOEF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IRCALCOEF'] = self.IRCALCOEF
        self.IRCALCOEFWR0 = RM_Register_MODEM_NS_IRCALCOEFWR0(self.zz_rmio, self.zz_label)
        self.zz_rdict['IRCALCOEFWR0'] = self.IRCALCOEFWR0
        self.ADCTRL1 = RM_Register_MODEM_NS_ADCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADCTRL1'] = self.ADCTRL1
        self.ADCTRL2 = RM_Register_MODEM_NS_ADCTRL2(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADCTRL2'] = self.ADCTRL2
        self.ADQUAL0 = RM_Register_MODEM_NS_ADQUAL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADQUAL0'] = self.ADQUAL0
        self.ADQUAL1 = RM_Register_MODEM_NS_ADQUAL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADQUAL1'] = self.ADQUAL1
        self.ADQUAL2 = RM_Register_MODEM_NS_ADQUAL2(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADQUAL2'] = self.ADQUAL2
        self.ADQUAL3 = RM_Register_MODEM_NS_ADQUAL3(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADQUAL3'] = self.ADQUAL3
        self.ADQUAL4 = RM_Register_MODEM_NS_ADQUAL4(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADQUAL4'] = self.ADQUAL4
        self.ADQUAL5 = RM_Register_MODEM_NS_ADQUAL5(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADQUAL5'] = self.ADQUAL5
        self.ADQUAL6 = RM_Register_MODEM_NS_ADQUAL6(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADQUAL6'] = self.ADQUAL6
        self.ADQUAL7 = RM_Register_MODEM_NS_ADQUAL7(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADQUAL7'] = self.ADQUAL7
        self.ADQUAL8 = RM_Register_MODEM_NS_ADQUAL8(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADQUAL8'] = self.ADQUAL8
        self.ADQUAL9 = RM_Register_MODEM_NS_ADQUAL9(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADQUAL9'] = self.ADQUAL9
        self.ADQUAL10 = RM_Register_MODEM_NS_ADQUAL10(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADQUAL10'] = self.ADQUAL10
        self.ADFSM0 = RM_Register_MODEM_NS_ADFSM0(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM0'] = self.ADFSM0
        self.ADFSM1 = RM_Register_MODEM_NS_ADFSM1(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM1'] = self.ADFSM1
        self.ADFSM2 = RM_Register_MODEM_NS_ADFSM2(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM2'] = self.ADFSM2
        self.ADFSM3 = RM_Register_MODEM_NS_ADFSM3(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM3'] = self.ADFSM3
        self.ADFSM4 = RM_Register_MODEM_NS_ADFSM4(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM4'] = self.ADFSM4
        self.ADFSM5 = RM_Register_MODEM_NS_ADFSM5(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM5'] = self.ADFSM5
        self.ADFSM6 = RM_Register_MODEM_NS_ADFSM6(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM6'] = self.ADFSM6
        self.ADFSM7 = RM_Register_MODEM_NS_ADFSM7(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM7'] = self.ADFSM7
        self.ADFSM8 = RM_Register_MODEM_NS_ADFSM8(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM8'] = self.ADFSM8
        self.ADFSM9 = RM_Register_MODEM_NS_ADFSM9(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM9'] = self.ADFSM9
        self.ADFSM10 = RM_Register_MODEM_NS_ADFSM10(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM10'] = self.ADFSM10
        self.ADFSM11 = RM_Register_MODEM_NS_ADFSM11(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM11'] = self.ADFSM11
        self.ADFSM12 = RM_Register_MODEM_NS_ADFSM12(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM12'] = self.ADFSM12
        self.ADFSM13 = RM_Register_MODEM_NS_ADFSM13(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM13'] = self.ADFSM13
        self.ADFSM14 = RM_Register_MODEM_NS_ADFSM14(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM14'] = self.ADFSM14
        self.ADFSM15 = RM_Register_MODEM_NS_ADFSM15(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM15'] = self.ADFSM15
        self.ADFSM16 = RM_Register_MODEM_NS_ADFSM16(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM16'] = self.ADFSM16
        self.ADFSM17 = RM_Register_MODEM_NS_ADFSM17(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM17'] = self.ADFSM17
        self.ADFSM18 = RM_Register_MODEM_NS_ADFSM18(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM18'] = self.ADFSM18
        self.ADFSM19 = RM_Register_MODEM_NS_ADFSM19(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM19'] = self.ADFSM19
        self.ADFSM20 = RM_Register_MODEM_NS_ADFSM20(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM20'] = self.ADFSM20
        self.ADFSM21 = RM_Register_MODEM_NS_ADFSM21(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM21'] = self.ADFSM21
        self.ADFSM22 = RM_Register_MODEM_NS_ADFSM22(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM22'] = self.ADFSM22
        self.ADFSM23 = RM_Register_MODEM_NS_ADFSM23(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM23'] = self.ADFSM23
        self.ADFSM24 = RM_Register_MODEM_NS_ADFSM24(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM24'] = self.ADFSM24
        self.ADFSM25 = RM_Register_MODEM_NS_ADFSM25(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM25'] = self.ADFSM25
        self.ADFSM26 = RM_Register_MODEM_NS_ADFSM26(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM26'] = self.ADFSM26
        self.ADFSM27 = RM_Register_MODEM_NS_ADFSM27(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM27'] = self.ADFSM27
        self.ADFSM28 = RM_Register_MODEM_NS_ADFSM28(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM28'] = self.ADFSM28
        self.ADFSM29 = RM_Register_MODEM_NS_ADFSM29(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM29'] = self.ADFSM29
        self.ADFSM30 = RM_Register_MODEM_NS_ADFSM30(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADFSM30'] = self.ADFSM30
        self.ADPC1 = RM_Register_MODEM_NS_ADPC1(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADPC1'] = self.ADPC1
        self.ADPC2 = RM_Register_MODEM_NS_ADPC2(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADPC2'] = self.ADPC2
        self.ADPC3 = RM_Register_MODEM_NS_ADPC3(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADPC3'] = self.ADPC3
        self.ADPC4 = RM_Register_MODEM_NS_ADPC4(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADPC4'] = self.ADPC4
        self.ADPC5 = RM_Register_MODEM_NS_ADPC5(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADPC5'] = self.ADPC5
        self.ADPC6 = RM_Register_MODEM_NS_ADPC6(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADPC6'] = self.ADPC6
        self.ADPC7 = RM_Register_MODEM_NS_ADPC7(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADPC7'] = self.ADPC7
        self.ADPC8 = RM_Register_MODEM_NS_ADPC8(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADPC8'] = self.ADPC8
        self.ADPC9 = RM_Register_MODEM_NS_ADPC9(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADPC9'] = self.ADPC9
        self.ADPC10 = RM_Register_MODEM_NS_ADPC10(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADPC10'] = self.ADPC10
        self.HADMCTRL0 = RM_Register_MODEM_NS_HADMCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMCTRL0'] = self.HADMCTRL0
        self.HADMCTRL1 = RM_Register_MODEM_NS_HADMCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMCTRL1'] = self.HADMCTRL1
        self.HADMSTATUS0 = RM_Register_MODEM_NS_HADMSTATUS0(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS0'] = self.HADMSTATUS0
        self.HADMSTATUS1 = RM_Register_MODEM_NS_HADMSTATUS1(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS1'] = self.HADMSTATUS1
        self.HADMSTATUS2 = RM_Register_MODEM_NS_HADMSTATUS2(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS2'] = self.HADMSTATUS2
        self.HADMSTATUS3 = RM_Register_MODEM_NS_HADMSTATUS3(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS3'] = self.HADMSTATUS3
        self.HADMSTATUS4 = RM_Register_MODEM_NS_HADMSTATUS4(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS4'] = self.HADMSTATUS4
        self.HADMSTATUS5 = RM_Register_MODEM_NS_HADMSTATUS5(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS5'] = self.HADMSTATUS5
        self.HADMSTATUS6 = RM_Register_MODEM_NS_HADMSTATUS6(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS6'] = self.HADMSTATUS6
        self.EHDSSSCTRL = RM_Register_MODEM_NS_EHDSSSCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['EHDSSSCTRL'] = self.EHDSSSCTRL
        self.EHDSSSCFG0 = RM_Register_MODEM_NS_EHDSSSCFG0(self.zz_rmio, self.zz_label)
        self.zz_rdict['EHDSSSCFG0'] = self.EHDSSSCFG0
        self.EHDSSSCFG1 = RM_Register_MODEM_NS_EHDSSSCFG1(self.zz_rmio, self.zz_label)
        self.zz_rdict['EHDSSSCFG1'] = self.EHDSSSCFG1
        self.EHDSSSCFG2 = RM_Register_MODEM_NS_EHDSSSCFG2(self.zz_rmio, self.zz_label)
        self.zz_rdict['EHDSSSCFG2'] = self.EHDSSSCFG2
        self.SYMBOL2CHIP0 = RM_Register_MODEM_NS_SYMBOL2CHIP0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIP0'] = self.SYMBOL2CHIP0
        self.SYMBOL2CHIP1 = RM_Register_MODEM_NS_SYMBOL2CHIP1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIP1'] = self.SYMBOL2CHIP1
        self.SYMBOL2CHIP2 = RM_Register_MODEM_NS_SYMBOL2CHIP2(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIP2'] = self.SYMBOL2CHIP2
        self.SYMBOL2CHIP3 = RM_Register_MODEM_NS_SYMBOL2CHIP3(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIP3'] = self.SYMBOL2CHIP3
        self.SYMBOL2CHIP4 = RM_Register_MODEM_NS_SYMBOL2CHIP4(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIP4'] = self.SYMBOL2CHIP4
        self.SYMBOL2CHIP5 = RM_Register_MODEM_NS_SYMBOL2CHIP5(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIP5'] = self.SYMBOL2CHIP5
        self.SYMBOL2CHIP6 = RM_Register_MODEM_NS_SYMBOL2CHIP6(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIP6'] = self.SYMBOL2CHIP6
        self.SYMBOL2CHIP7 = RM_Register_MODEM_NS_SYMBOL2CHIP7(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIP7'] = self.SYMBOL2CHIP7
        self.SYMBOL2CHIP8 = RM_Register_MODEM_NS_SYMBOL2CHIP8(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIP8'] = self.SYMBOL2CHIP8
        self.SYMBOL2CHIP9 = RM_Register_MODEM_NS_SYMBOL2CHIP9(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIP9'] = self.SYMBOL2CHIP9
        self.SYMBOL2CHIPA = RM_Register_MODEM_NS_SYMBOL2CHIPA(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIPA'] = self.SYMBOL2CHIPA
        self.SYMBOL2CHIPB = RM_Register_MODEM_NS_SYMBOL2CHIPB(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIPB'] = self.SYMBOL2CHIPB
        self.SYMBOL2CHIPC = RM_Register_MODEM_NS_SYMBOL2CHIPC(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIPC'] = self.SYMBOL2CHIPC
        self.SYMBOL2CHIPD = RM_Register_MODEM_NS_SYMBOL2CHIPD(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIPD'] = self.SYMBOL2CHIPD
        self.SYMBOL2CHIPE = RM_Register_MODEM_NS_SYMBOL2CHIPE(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIPE'] = self.SYMBOL2CHIPE
        self.SYMBOL2CHIPF = RM_Register_MODEM_NS_SYMBOL2CHIPF(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMBOL2CHIPF'] = self.SYMBOL2CHIPF
        self.SPARE = RM_Register_MODEM_NS_SPARE(self.zz_rmio, self.zz_label)
        self.zz_rdict['SPARE'] = self.SPARE
        self.SYNC0 = RM_Register_MODEM_NS_SYNC0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNC0'] = self.SYNC0
        self.SYNC1 = RM_Register_MODEM_NS_SYNC1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNC1'] = self.SYNC1
        self.SYNC2 = RM_Register_MODEM_NS_SYNC2(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNC2'] = self.SYNC2
        self.SYNCWORDCTRL = RM_Register_MODEM_NS_SYNCWORDCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNCWORDCTRL'] = self.SYNCWORDCTRL
        self.TXCORR = RM_Register_MODEM_NS_TXCORR(self.zz_rmio, self.zz_label)
        self.zz_rdict['TXCORR'] = self.TXCORR
        self.TXMISC = RM_Register_MODEM_NS_TXMISC(self.zz_rmio, self.zz_label)
        self.zz_rdict['TXMISC'] = self.TXMISC
        self.__dict__['zz_frozen'] = True