
# -*- coding: utf-8 -*-

__all__ = [ 'RM_Peripheral_RAC_NS' ]

from . static import Base_RM_Peripheral
from . RAC_NS_register import *

class RM_Peripheral_RAC_NS(Base_RM_Peripheral):
    def __init__(self, rmio, label):
        self.__dict__['zz_frozen'] = False
        super(RM_Peripheral_RAC_NS, self).__init__(rmio, label,
            0xB0220000, 'RAC_NS',
            u"",
            [])
        self.IPVERSION = RM_Register_RAC_NS_IPVERSION(self.zz_rmio, self.zz_label)
        self.zz_rdict['IPVERSION'] = self.IPVERSION
        self.EN = RM_Register_RAC_NS_EN(self.zz_rmio, self.zz_label)
        self.zz_rdict['EN'] = self.EN
        self.RXENSRCEN = RM_Register_RAC_NS_RXENSRCEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['RXENSRCEN'] = self.RXENSRCEN
        self.STATUS = RM_Register_RAC_NS_STATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS'] = self.STATUS
        self.CMD = RM_Register_RAC_NS_CMD(self.zz_rmio, self.zz_label)
        self.zz_rdict['CMD'] = self.CMD
        self.CTRL = RM_Register_RAC_NS_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL'] = self.CTRL
        self.FORCESTATE = RM_Register_RAC_NS_FORCESTATE(self.zz_rmio, self.zz_label)
        self.zz_rdict['FORCESTATE'] = self.FORCESTATE
        self.IF = RM_Register_RAC_NS_IF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IF'] = self.IF
        self.IEN = RM_Register_RAC_NS_IEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['IEN'] = self.IEN
        self.TESTCTRL = RM_Register_RAC_NS_TESTCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['TESTCTRL'] = self.TESTCTRL
        self.SEQIF = RM_Register_RAC_NS_SEQIF(self.zz_rmio, self.zz_label)
        self.zz_rdict['SEQIF'] = self.SEQIF
        self.SEQIEN = RM_Register_RAC_NS_SEQIEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['SEQIEN'] = self.SEQIEN
        self.STATUS1 = RM_Register_RAC_NS_STATUS1(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS1'] = self.STATUS1
        self.FSWIF = RM_Register_RAC_NS_FSWIF(self.zz_rmio, self.zz_label)
        self.zz_rdict['FSWIF'] = self.FSWIF
        self.FSWIEN = RM_Register_RAC_NS_FSWIEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['FSWIEN'] = self.FSWIEN
        self.TXWRAPUPNEXT = RM_Register_RAC_NS_TXWRAPUPNEXT(self.zz_rmio, self.zz_label)
        self.zz_rdict['TXWRAPUPNEXT'] = self.TXWRAPUPNEXT
        self.RXWRAPUPNEXT = RM_Register_RAC_NS_RXWRAPUPNEXT(self.zz_rmio, self.zz_label)
        self.zz_rdict['RXWRAPUPNEXT'] = self.RXWRAPUPNEXT
        self.SEQEND = RM_Register_RAC_NS_SEQEND(self.zz_rmio, self.zz_label)
        self.zz_rdict['SEQEND'] = self.SEQEND
        self.SEQENDEN = RM_Register_RAC_NS_SEQENDEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['SEQENDEN'] = self.SEQENDEN
        self.FRCCLKDIS = RM_Register_RAC_NS_FRCCLKDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['FRCCLKDIS'] = self.FRCCLKDIS
        self.BUFCCLKDIS = RM_Register_RAC_NS_BUFCCLKDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUFCCLKDIS'] = self.BUFCCLKDIS
        self.STIMER = RM_Register_RAC_NS_STIMER(self.zz_rmio, self.zz_label)
        self.zz_rdict['STIMER'] = self.STIMER
        self.STIMERCOMP = RM_Register_RAC_NS_STIMERCOMP(self.zz_rmio, self.zz_label)
        self.zz_rdict['STIMERCOMP'] = self.STIMERCOMP
        self.SEQCTRL = RM_Register_RAC_NS_SEQCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['SEQCTRL'] = self.SEQCTRL
        self.PRESC = RM_Register_RAC_NS_PRESC(self.zz_rmio, self.zz_label)
        self.zz_rdict['PRESC'] = self.PRESC
        self.SR0 = RM_Register_RAC_NS_SR0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SR0'] = self.SR0
        self.SR1 = RM_Register_RAC_NS_SR1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SR1'] = self.SR1
        self.SR2 = RM_Register_RAC_NS_SR2(self.zz_rmio, self.zz_label)
        self.zz_rdict['SR2'] = self.SR2
        self.SR3 = RM_Register_RAC_NS_SR3(self.zz_rmio, self.zz_label)
        self.zz_rdict['SR3'] = self.SR3
        self.FRCTXWORD = RM_Register_RAC_NS_FRCTXWORD(self.zz_rmio, self.zz_label)
        self.zz_rdict['FRCTXWORD'] = self.FRCTXWORD
        self.FRCRXWORD = RM_Register_RAC_NS_FRCRXWORD(self.zz_rmio, self.zz_label)
        self.zz_rdict['FRCRXWORD'] = self.FRCRXWORD
        self.EM1PCSR = RM_Register_RAC_NS_EM1PCSR(self.zz_rmio, self.zz_label)
        self.zz_rdict['EM1PCSR'] = self.EM1PCSR
        self.HYDRARAMREMAP = RM_Register_RAC_NS_HYDRARAMREMAP(self.zz_rmio, self.zz_label)
        self.zz_rdict['HYDRARAMREMAP'] = self.HYDRARAMREMAP
        self.SYNTHENCTRL = RM_Register_RAC_NS_SYNTHENCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNTHENCTRL'] = self.SYNTHENCTRL
        self.RFSTATUS = RM_Register_RAC_NS_RFSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['RFSTATUS'] = self.RFSTATUS
        self.STATUS2 = RM_Register_RAC_NS_STATUS2(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS2'] = self.STATUS2
        self.IFPGACTRL = RM_Register_RAC_NS_IFPGACTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['IFPGACTRL'] = self.IFPGACTRL
        self.PAENCTRL = RM_Register_RAC_NS_PAENCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PAENCTRL'] = self.PAENCTRL
        self.APC = RM_Register_RAC_NS_APC(self.zz_rmio, self.zz_label)
        self.zz_rdict['APC'] = self.APC
        self.ANTDIV = RM_Register_RAC_NS_ANTDIV(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTDIV'] = self.ANTDIV
        self.AUXADCEN = RM_Register_RAC_NS_AUXADCEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['AUXADCEN'] = self.AUXADCEN
        self.AUXADCCTRL0 = RM_Register_RAC_NS_AUXADCCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['AUXADCCTRL0'] = self.AUXADCCTRL0
        self.AUXADCCTRL1 = RM_Register_RAC_NS_AUXADCCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['AUXADCCTRL1'] = self.AUXADCCTRL1
        self.AUXADCOUT = RM_Register_RAC_NS_AUXADCOUT(self.zz_rmio, self.zz_label)
        self.zz_rdict['AUXADCOUT'] = self.AUXADCOUT
        self.CLKMULTEN0 = RM_Register_RAC_NS_CLKMULTEN0(self.zz_rmio, self.zz_label)
        self.zz_rdict['CLKMULTEN0'] = self.CLKMULTEN0
        self.CLKMULTEN1 = RM_Register_RAC_NS_CLKMULTEN1(self.zz_rmio, self.zz_label)
        self.zz_rdict['CLKMULTEN1'] = self.CLKMULTEN1
        self.CLKMULTCTRL = RM_Register_RAC_NS_CLKMULTCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CLKMULTCTRL'] = self.CLKMULTCTRL
        self.CLKMULTSTATUS = RM_Register_RAC_NS_CLKMULTSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['CLKMULTSTATUS'] = self.CLKMULTSTATUS
        self.ADCSTATUS = RM_Register_RAC_NS_ADCSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADCSTATUS'] = self.ADCSTATUS
        self.LNAMIXTRIM0 = RM_Register_RAC_NS_LNAMIXTRIM0(self.zz_rmio, self.zz_label)
        self.zz_rdict['LNAMIXTRIM0'] = self.LNAMIXTRIM0
        self.LNAMIXTRIM1 = RM_Register_RAC_NS_LNAMIXTRIM1(self.zz_rmio, self.zz_label)
        self.zz_rdict['LNAMIXTRIM1'] = self.LNAMIXTRIM1
        self.LNAMIXCAL = RM_Register_RAC_NS_LNAMIXCAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['LNAMIXCAL'] = self.LNAMIXCAL
        self.PRECTRL = RM_Register_RAC_NS_PRECTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PRECTRL'] = self.PRECTRL
        self.PATRIM0 = RM_Register_RAC_NS_PATRIM0(self.zz_rmio, self.zz_label)
        self.zz_rdict['PATRIM0'] = self.PATRIM0
        self.TXRAMP = RM_Register_RAC_NS_TXRAMP(self.zz_rmio, self.zz_label)
        self.zz_rdict['TXRAMP'] = self.TXRAMP
        self.RADIOEN = RM_Register_RAC_NS_RADIOEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['RADIOEN'] = self.RADIOEN
        self.RFPATHEN0 = RM_Register_RAC_NS_RFPATHEN0(self.zz_rmio, self.zz_label)
        self.zz_rdict['RFPATHEN0'] = self.RFPATHEN0
        self.RFPATHEN1 = RM_Register_RAC_NS_RFPATHEN1(self.zz_rmio, self.zz_label)
        self.zz_rdict['RFPATHEN1'] = self.RFPATHEN1
        self.RX = RM_Register_RAC_NS_RX(self.zz_rmio, self.zz_label)
        self.zz_rdict['RX'] = self.RX
        self.TX = RM_Register_RAC_NS_TX(self.zz_rmio, self.zz_label)
        self.zz_rdict['TX'] = self.TX
        self.SYDEBUG = RM_Register_RAC_NS_SYDEBUG(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYDEBUG'] = self.SYDEBUG
        self.SYTRIM0 = RM_Register_RAC_NS_SYTRIM0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYTRIM0'] = self.SYTRIM0
        self.SYTRIM1 = RM_Register_RAC_NS_SYTRIM1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYTRIM1'] = self.SYTRIM1
        self.SYLOEN0 = RM_Register_RAC_NS_SYLOEN0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYLOEN0'] = self.SYLOEN0
        self.SYMMDCTRL = RM_Register_RAC_NS_SYMMDCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYMMDCTRL'] = self.SYMMDCTRL
        self.DIGCLKRETIMECTRL = RM_Register_RAC_NS_DIGCLKRETIMECTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIGCLKRETIMECTRL'] = self.DIGCLKRETIMECTRL
        self.DIGCLKRETIMESTATUS = RM_Register_RAC_NS_DIGCLKRETIMESTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIGCLKRETIMESTATUS'] = self.DIGCLKRETIMESTATUS
        self.XORETIMECTRL = RM_Register_RAC_NS_XORETIMECTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['XORETIMECTRL'] = self.XORETIMECTRL
        self.XORETIMESTATUS = RM_Register_RAC_NS_XORETIMESTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['XORETIMESTATUS'] = self.XORETIMESTATUS
        self.AGCOVERWRITE0 = RM_Register_RAC_NS_AGCOVERWRITE0(self.zz_rmio, self.zz_label)
        self.zz_rdict['AGCOVERWRITE0'] = self.AGCOVERWRITE0
        self.AGCOVERWRITE1 = RM_Register_RAC_NS_AGCOVERWRITE1(self.zz_rmio, self.zz_label)
        self.zz_rdict['AGCOVERWRITE1'] = self.AGCOVERWRITE1
        self.SPARE = RM_Register_RAC_NS_SPARE(self.zz_rmio, self.zz_label)
        self.zz_rdict['SPARE'] = self.SPARE
        self.MIXDACTRIM = RM_Register_RAC_NS_MIXDACTRIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['MIXDACTRIM'] = self.MIXDACTRIM
        self.SYTRIM2 = RM_Register_RAC_NS_SYTRIM2(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYTRIM2'] = self.SYTRIM2
        self.SYDLFCTRL1 = RM_Register_RAC_NS_SYDLFCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYDLFCTRL1'] = self.SYDLFCTRL1
        self.SYSTATUS = RM_Register_RAC_NS_SYSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYSTATUS'] = self.SYSTATUS
        self.SYCTRL2 = RM_Register_RAC_NS_SYCTRL2(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYCTRL2'] = self.SYCTRL2
        self.TIATRIM0 = RM_Register_RAC_NS_TIATRIM0(self.zz_rmio, self.zz_label)
        self.zz_rdict['TIATRIM0'] = self.TIATRIM0
        self.TIAEN = RM_Register_RAC_NS_TIAEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['TIAEN'] = self.TIAEN
        self.VTRCTRL0 = RM_Register_RAC_NS_VTRCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTRCTRL0'] = self.VTRCTRL0
        self.AUXADCCAL = RM_Register_RAC_NS_AUXADCCAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['AUXADCCAL'] = self.AUXADCCAL
        self.AUXADCCTRL2 = RM_Register_RAC_NS_AUXADCCTRL2(self.zz_rmio, self.zz_label)
        self.zz_rdict['AUXADCCTRL2'] = self.AUXADCCTRL2
        self.LNAMIXEN0 = RM_Register_RAC_NS_LNAMIXEN0(self.zz_rmio, self.zz_label)
        self.zz_rdict['LNAMIXEN0'] = self.LNAMIXEN0
        self.MIXDACEN = RM_Register_RAC_NS_MIXDACEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['MIXDACEN'] = self.MIXDACEN
        self.SYCTRL1 = RM_Register_RAC_NS_SYCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYCTRL1'] = self.SYCTRL1
        self.TX0DBMEN = RM_Register_RAC_NS_TX0DBMEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['TX0DBMEN'] = self.TX0DBMEN
        self.TX0DBMCTRL = RM_Register_RAC_NS_TX0DBMCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['TX0DBMCTRL'] = self.TX0DBMCTRL
        self.TX0DBMTRIM1 = RM_Register_RAC_NS_TX0DBMTRIM1(self.zz_rmio, self.zz_label)
        self.zz_rdict['TX0DBMTRIM1'] = self.TX0DBMTRIM1
        self.TX0DBMTRIM0 = RM_Register_RAC_NS_TX0DBMTRIM0(self.zz_rmio, self.zz_label)
        self.zz_rdict['TX0DBMTRIM0'] = self.TX0DBMTRIM0
        self.TX10DBMEN = RM_Register_RAC_NS_TX10DBMEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['TX10DBMEN'] = self.TX10DBMEN
        self.TX10DBMCTRL0 = RM_Register_RAC_NS_TX10DBMCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['TX10DBMCTRL0'] = self.TX10DBMCTRL0
        self.TX10DBMTRIM1 = RM_Register_RAC_NS_TX10DBMTRIM1(self.zz_rmio, self.zz_label)
        self.zz_rdict['TX10DBMTRIM1'] = self.TX10DBMTRIM1
        self.TX10DBMTRIM2 = RM_Register_RAC_NS_TX10DBMTRIM2(self.zz_rmio, self.zz_label)
        self.zz_rdict['TX10DBMTRIM2'] = self.TX10DBMTRIM2
        self.PREREGTRIM = RM_Register_RAC_NS_PREREGTRIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['PREREGTRIM'] = self.PREREGTRIM
        self.MIXDACTRIM1 = RM_Register_RAC_NS_MIXDACTRIM1(self.zz_rmio, self.zz_label)
        self.zz_rdict['MIXDACTRIM1'] = self.MIXDACTRIM1
        self.SYDLF1 = RM_Register_RAC_NS_SYDLF1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYDLF1'] = self.SYDLF1
        self.SPARE1 = RM_Register_RAC_NS_SPARE1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SPARE1'] = self.SPARE1
        self.PREREGSTATUS = RM_Register_RAC_NS_PREREGSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PREREGSTATUS'] = self.PREREGSTATUS
        self.VTRTRIM = RM_Register_RAC_NS_VTRTRIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTRTRIM'] = self.VTRTRIM
        self.ADCCTRL0 = RM_Register_RAC_NS_ADCCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADCCTRL0'] = self.ADCCTRL0
        self.ADCCTRL1 = RM_Register_RAC_NS_ADCCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADCCTRL1'] = self.ADCCTRL1
        self.ADCEN0 = RM_Register_RAC_NS_ADCEN0(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADCEN0'] = self.ADCEN0
        self.ADCTRIM0 = RM_Register_RAC_NS_ADCTRIM0(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADCTRIM0'] = self.ADCTRIM0
        self.ADCCTRL2 = RM_Register_RAC_NS_ADCCTRL2(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADCCTRL2'] = self.ADCCTRL2
        self.LNAMIXEN1 = RM_Register_RAC_NS_LNAMIXEN1(self.zz_rmio, self.zz_label)
        self.zz_rdict['LNAMIXEN1'] = self.LNAMIXEN1
        self.LNAMIXCTRL0 = RM_Register_RAC_NS_LNAMIXCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['LNAMIXCTRL0'] = self.LNAMIXCTRL0
        self.LNAMIXCTRL1 = RM_Register_RAC_NS_LNAMIXCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['LNAMIXCTRL1'] = self.LNAMIXCTRL1
        self.PREREGEN = RM_Register_RAC_NS_PREREGEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PREREGEN'] = self.PREREGEN
        self.PREDEBUG = RM_Register_RAC_NS_PREDEBUG(self.zz_rmio, self.zz_label)
        self.zz_rdict['PREDEBUG'] = self.PREDEBUG
        self.SYDLFCTRL0 = RM_Register_RAC_NS_SYDLFCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYDLFCTRL0'] = self.SYDLFCTRL0
        self.SYEN0 = RM_Register_RAC_NS_SYEN0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYEN0'] = self.SYEN0
        self.SYEN1 = RM_Register_RAC_NS_SYEN1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYEN1'] = self.SYEN1
        self.SYEN2 = RM_Register_RAC_NS_SYEN2(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYEN2'] = self.SYEN2
        self.SYCTRL0 = RM_Register_RAC_NS_SYCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYCTRL0'] = self.SYCTRL0
        self.SYLOEN1 = RM_Register_RAC_NS_SYLOEN1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYLOEN1'] = self.SYLOEN1
        self.SYLOEN2 = RM_Register_RAC_NS_SYLOEN2(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYLOEN2'] = self.SYLOEN2
        self.SYLOCTRL0 = RM_Register_RAC_NS_SYLOCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYLOCTRL0'] = self.SYLOCTRL0
        self.SYLOCTRL1 = RM_Register_RAC_NS_SYLOCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYLOCTRL1'] = self.SYLOCTRL1
        self.SYLOTRIM0 = RM_Register_RAC_NS_SYLOTRIM0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYLOTRIM0'] = self.SYLOTRIM0
        self.SYTRIM3 = RM_Register_RAC_NS_SYTRIM3(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYTRIM3'] = self.SYTRIM3
        self.TIACTRL0 = RM_Register_RAC_NS_TIACTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['TIACTRL0'] = self.TIACTRL0
        self.TIACTRL1 = RM_Register_RAC_NS_TIACTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['TIACTRL1'] = self.TIACTRL1
        self.TX10DBMCTRL1 = RM_Register_RAC_NS_TX10DBMCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['TX10DBMCTRL1'] = self.TX10DBMCTRL1
        self.TX10DBMTRIM0 = RM_Register_RAC_NS_TX10DBMTRIM0(self.zz_rmio, self.zz_label)
        self.zz_rdict['TX10DBMTRIM0'] = self.TX10DBMTRIM0
        self.SYCTRLTX0 = RM_Register_RAC_NS_SYCTRLTX0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYCTRLTX0'] = self.SYCTRLTX0
        self.SYLOCTRLTX0 = RM_Register_RAC_NS_SYLOCTRLTX0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYLOCTRLTX0'] = self.SYLOCTRLTX0
        self.SYLOCTRLTX1 = RM_Register_RAC_NS_SYLOCTRLTX1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYLOCTRLTX1'] = self.SYLOCTRLTX1
        self.CLKMULTEN2 = RM_Register_RAC_NS_CLKMULTEN2(self.zz_rmio, self.zz_label)
        self.zz_rdict['CLKMULTEN2'] = self.CLKMULTEN2
        self.SCRATCH0 = RM_Register_RAC_NS_SCRATCH0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SCRATCH0'] = self.SCRATCH0
        self.SCRATCH1 = RM_Register_RAC_NS_SCRATCH1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SCRATCH1'] = self.SCRATCH1
        self.SCRATCH2 = RM_Register_RAC_NS_SCRATCH2(self.zz_rmio, self.zz_label)
        self.zz_rdict['SCRATCH2'] = self.SCRATCH2
        self.SCRATCH3 = RM_Register_RAC_NS_SCRATCH3(self.zz_rmio, self.zz_label)
        self.zz_rdict['SCRATCH3'] = self.SCRATCH3
        self.SCRATCH4 = RM_Register_RAC_NS_SCRATCH4(self.zz_rmio, self.zz_label)
        self.zz_rdict['SCRATCH4'] = self.SCRATCH4
        self.SCRATCH5 = RM_Register_RAC_NS_SCRATCH5(self.zz_rmio, self.zz_label)
        self.zz_rdict['SCRATCH5'] = self.SCRATCH5
        self.SCRATCH6 = RM_Register_RAC_NS_SCRATCH6(self.zz_rmio, self.zz_label)
        self.zz_rdict['SCRATCH6'] = self.SCRATCH6
        self.SCRATCH7 = RM_Register_RAC_NS_SCRATCH7(self.zz_rmio, self.zz_label)
        self.zz_rdict['SCRATCH7'] = self.SCRATCH7
        self.FSWCTRL = RM_Register_RAC_NS_FSWCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['FSWCTRL'] = self.FSWCTRL
        self.THMSW = RM_Register_RAC_NS_THMSW(self.zz_rmio, self.zz_label)
        self.zz_rdict['THMSW'] = self.THMSW
        self.DIAGAALTEN = RM_Register_RAC_NS_DIAGAALTEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIAGAALTEN'] = self.DIAGAALTEN
        self.DIAGAALTSEL = RM_Register_RAC_NS_DIAGAALTSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIAGAALTSEL'] = self.DIAGAALTSEL
        self.DIAGAALTBRIDGECTRL = RM_Register_RAC_NS_DIAGAALTBRIDGECTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIAGAALTBRIDGECTRL'] = self.DIAGAALTBRIDGECTRL
        self.RFLOCK0 = RM_Register_RAC_NS_RFLOCK0(self.zz_rmio, self.zz_label)
        self.zz_rdict['RFLOCK0'] = self.RFLOCK0
        self.RFLOCK1 = RM_Register_RAC_NS_RFLOCK1(self.zz_rmio, self.zz_label)
        self.zz_rdict['RFLOCK1'] = self.RFLOCK1
        self.__dict__['zz_frozen'] = True