/***************************************************************************//**
 * @brief
 *******************************************************************************
 * # License
 * <b>Copyright 2018 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * SPDX-License-Identifier: Zlib
 *
 * The licensor of this software is Silicon Laboratories Inc.
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 ******************************************************************************/

// *** Generated file. Do not edit! ***
// vNCP Version: 1.0

#include PLATFORM_HEADER
#include "ember-types.h"

// These 2 defines should be generated by actually setting them to the maximum
// needed size for both APIs and stack callbacks. For now they are set to some
// large value.
#define MAX_STACK_API_COMMAND_SIZE                      160
#define MAX_STACK_CALLBACK_COMMAND_SIZE                 160

void emAfPluginCmsisStackStatusHandler(EmberStatus status);
void emAfPluginCmsisChildJoinHandler(EmberNodeType nodeType,
                                     EmberNodeId nodeId);
void emAfPluginCmsisRadioNeedsCalibratingHandler();
void emAfPluginCmsisStackIsrHandler();
bool emAfPluginCmsisStackIdleHandler(uint32_t *idleTimeMs);
void emAfPluginCmsisMessageSentHandler(EmberStatus status,
                                       EmberOutgoingMessage *message);
void emAfPluginCmsisIncomingMessageHandler(EmberIncomingMessage *message);
void emAfPluginCmsisIncomingMacMessageHandler(EmberIncomingMacMessage *message);
void emAfPluginCmsisMacMessageSentHandler(EmberStatus status,
                                          EmberOutgoingMacMessage *message);
void emAfPluginCmsisIncomingBeaconHandler(EmberPanId panId,
                                          EmberMacAddress *source,
                                          int8_t rssi,
                                          bool permitJoining,
                                          uint8_t beaconFieldsLength,
                                          uint8_t *beaconFields,
                                          uint8_t beaconPayloadLength,
                                          uint8_t *beaconPayload);
void emAfPluginCmsisActiveScanCompleteHandler();
void emAfPluginCmsisEnergyScanCompleteHandler(int8_t mean,
                                              int8_t min,
                                              int8_t max,
                                              uint16_t variance);
void emAfPluginCmsisFrequencyHoppingStartClientCompleteHandler(EmberStatus status);
