
# -*- coding: utf-8 -*-

__all__ = [ 'RM_Peripheral_MODEM_NS' ]

from . static import Base_RM_Peripheral
from . MODEM_NS_register import *

class RM_Peripheral_MODEM_NS(Base_RM_Peripheral):
    def __init__(self, rmio, label):
        self.__dict__['zz_frozen'] = False
        super(RM_Peripheral_MODEM_NS, self).__init__(rmio, label,
            0xB8014000, 'MODEM_NS',
            u"",
            [])
        self.IPVERSION = RM_Register_MODEM_NS_IPVERSION(self.zz_rmio, self.zz_label)
        self.zz_rdict['IPVERSION'] = self.IPVERSION
        self.EN = RM_Register_MODEM_NS_EN(self.zz_rmio, self.zz_label)
        self.zz_rdict['EN'] = self.EN
        self.STATUS = RM_Register_MODEM_NS_STATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS'] = self.STATUS
        self.TIMDETSTATUS = RM_Register_MODEM_NS_TIMDETSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['TIMDETSTATUS'] = self.TIMDETSTATUS
        self.FREQOFFEST = RM_Register_MODEM_NS_FREQOFFEST(self.zz_rmio, self.zz_label)
        self.zz_rdict['FREQOFFEST'] = self.FREQOFFEST
        self.AFCADJRX = RM_Register_MODEM_NS_AFCADJRX(self.zz_rmio, self.zz_label)
        self.zz_rdict['AFCADJRX'] = self.AFCADJRX
        self.AFCADJTX = RM_Register_MODEM_NS_AFCADJTX(self.zz_rmio, self.zz_label)
        self.zz_rdict['AFCADJTX'] = self.AFCADJTX
        self.MIXCTRL = RM_Register_MODEM_NS_MIXCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['MIXCTRL'] = self.MIXCTRL
        self.CTRL0 = RM_Register_MODEM_NS_CTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL0'] = self.CTRL0
        self.CTRL1 = RM_Register_MODEM_NS_CTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL1'] = self.CTRL1
        self.CTRL2 = RM_Register_MODEM_NS_CTRL2(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL2'] = self.CTRL2
        self.CTRL3 = RM_Register_MODEM_NS_CTRL3(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL3'] = self.CTRL3
        self.CTRL4 = RM_Register_MODEM_NS_CTRL4(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL4'] = self.CTRL4
        self.CTRL5 = RM_Register_MODEM_NS_CTRL5(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL5'] = self.CTRL5
        self.CTRL6 = RM_Register_MODEM_NS_CTRL6(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL6'] = self.CTRL6
        self.TXBR = RM_Register_MODEM_NS_TXBR(self.zz_rmio, self.zz_label)
        self.zz_rdict['TXBR'] = self.TXBR
        self.RXBR = RM_Register_MODEM_NS_RXBR(self.zz_rmio, self.zz_label)
        self.zz_rdict['RXBR'] = self.RXBR
        self.CF = RM_Register_MODEM_NS_CF(self.zz_rmio, self.zz_label)
        self.zz_rdict['CF'] = self.CF
        self.PRE = RM_Register_MODEM_NS_PRE(self.zz_rmio, self.zz_label)
        self.zz_rdict['PRE'] = self.PRE
        self.SYNC0 = RM_Register_MODEM_NS_SYNC0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNC0'] = self.SYNC0
        self.SYNC1 = RM_Register_MODEM_NS_SYNC1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNC1'] = self.SYNC1
        self.TIMING = RM_Register_MODEM_NS_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['TIMING'] = self.TIMING
        self.DSSS0 = RM_Register_MODEM_NS_DSSS0(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSSS0'] = self.DSSS0
        self.MODINDEX = RM_Register_MODEM_NS_MODINDEX(self.zz_rmio, self.zz_label)
        self.zz_rdict['MODINDEX'] = self.MODINDEX
        self.AFC = RM_Register_MODEM_NS_AFC(self.zz_rmio, self.zz_label)
        self.zz_rdict['AFC'] = self.AFC
        self.AFCADJLIM = RM_Register_MODEM_NS_AFCADJLIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['AFCADJLIM'] = self.AFCADJLIM
        self.SHAPING0 = RM_Register_MODEM_NS_SHAPING0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING0'] = self.SHAPING0
        self.SHAPING1 = RM_Register_MODEM_NS_SHAPING1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING1'] = self.SHAPING1
        self.SHAPING2 = RM_Register_MODEM_NS_SHAPING2(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING2'] = self.SHAPING2
        self.SHAPING3 = RM_Register_MODEM_NS_SHAPING3(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING3'] = self.SHAPING3
        self.SHAPING4 = RM_Register_MODEM_NS_SHAPING4(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING4'] = self.SHAPING4
        self.SHAPING5 = RM_Register_MODEM_NS_SHAPING5(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING5'] = self.SHAPING5
        self.SHAPING6 = RM_Register_MODEM_NS_SHAPING6(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING6'] = self.SHAPING6
        self.SHAPING7 = RM_Register_MODEM_NS_SHAPING7(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING7'] = self.SHAPING7
        self.SHAPING8 = RM_Register_MODEM_NS_SHAPING8(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING8'] = self.SHAPING8
        self.SHAPING9 = RM_Register_MODEM_NS_SHAPING9(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING9'] = self.SHAPING9
        self.SHAPING10 = RM_Register_MODEM_NS_SHAPING10(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING10'] = self.SHAPING10
        self.SHAPING11 = RM_Register_MODEM_NS_SHAPING11(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING11'] = self.SHAPING11
        self.RAMPCTRL = RM_Register_MODEM_NS_RAMPCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['RAMPCTRL'] = self.RAMPCTRL
        self.RAMPLEV = RM_Register_MODEM_NS_RAMPLEV(self.zz_rmio, self.zz_label)
        self.zz_rdict['RAMPLEV'] = self.RAMPLEV
        self.DCCOMP = RM_Register_MODEM_NS_DCCOMP(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCCOMP'] = self.DCCOMP
        self.DCCOMPFILTINIT = RM_Register_MODEM_NS_DCCOMPFILTINIT(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCCOMPFILTINIT'] = self.DCCOMPFILTINIT
        self.DCESTI = RM_Register_MODEM_NS_DCESTI(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCESTI'] = self.DCESTI
        self.SRCCHF = RM_Register_MODEM_NS_SRCCHF(self.zz_rmio, self.zz_label)
        self.zz_rdict['SRCCHF'] = self.SRCCHF
        self.DSATHD0 = RM_Register_MODEM_NS_DSATHD0(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD0'] = self.DSATHD0
        self.DSATHD1 = RM_Register_MODEM_NS_DSATHD1(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD1'] = self.DSATHD1
        self.DSACTRL = RM_Register_MODEM_NS_DSACTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSACTRL'] = self.DSACTRL
        self.VITERBIDEMOD = RM_Register_MODEM_NS_VITERBIDEMOD(self.zz_rmio, self.zz_label)
        self.zz_rdict['VITERBIDEMOD'] = self.VITERBIDEMOD
        self.VTCORRCFG0 = RM_Register_MODEM_NS_VTCORRCFG0(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTCORRCFG0'] = self.VTCORRCFG0
        self.DIGMIXCTRL = RM_Register_MODEM_NS_DIGMIXCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIGMIXCTRL'] = self.DIGMIXCTRL
        self.VTCORRCFG1 = RM_Register_MODEM_NS_VTCORRCFG1(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTCORRCFG1'] = self.VTCORRCFG1
        self.VTTRACK = RM_Register_MODEM_NS_VTTRACK(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTTRACK'] = self.VTTRACK
        self.BREST = RM_Register_MODEM_NS_BREST(self.zz_rmio, self.zz_label)
        self.zz_rdict['BREST'] = self.BREST
        self.AUTOCG = RM_Register_MODEM_NS_AUTOCG(self.zz_rmio, self.zz_label)
        self.zz_rdict['AUTOCG'] = self.AUTOCG
        self.CGCLKSTOP = RM_Register_MODEM_NS_CGCLKSTOP(self.zz_rmio, self.zz_label)
        self.zz_rdict['CGCLKSTOP'] = self.CGCLKSTOP
        self.DSATHD2 = RM_Register_MODEM_NS_DSATHD2(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD2'] = self.DSATHD2
        self.DIRECTMODE = RM_Register_MODEM_NS_DIRECTMODE(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIRECTMODE'] = self.DIRECTMODE
        self.LONGRANGE = RM_Register_MODEM_NS_LONGRANGE(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE'] = self.LONGRANGE
        self.LONGRANGE1 = RM_Register_MODEM_NS_LONGRANGE1(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE1'] = self.LONGRANGE1
        self.LONGRANGE2 = RM_Register_MODEM_NS_LONGRANGE2(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE2'] = self.LONGRANGE2
        self.LONGRANGE3 = RM_Register_MODEM_NS_LONGRANGE3(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE3'] = self.LONGRANGE3
        self.LONGRANGE4 = RM_Register_MODEM_NS_LONGRANGE4(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE4'] = self.LONGRANGE4
        self.LONGRANGE5 = RM_Register_MODEM_NS_LONGRANGE5(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE5'] = self.LONGRANGE5
        self.LONGRANGE6 = RM_Register_MODEM_NS_LONGRANGE6(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE6'] = self.LONGRANGE6
        self.LRFRC = RM_Register_MODEM_NS_LRFRC(self.zz_rmio, self.zz_label)
        self.zz_rdict['LRFRC'] = self.LRFRC
        self.DSATHD3 = RM_Register_MODEM_NS_DSATHD3(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD3'] = self.DSATHD3
        self.DSATHD4 = RM_Register_MODEM_NS_DSATHD4(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD4'] = self.DSATHD4
        self.VTBLETIMING = RM_Register_MODEM_NS_VTBLETIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTBLETIMING'] = self.VTBLETIMING
        self.IF = RM_Register_MODEM_NS_IF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IF'] = self.IF
        self.IEN = RM_Register_MODEM_NS_IEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['IEN'] = self.IEN
        self.CMD = RM_Register_MODEM_NS_CMD(self.zz_rmio, self.zz_label)
        self.zz_rdict['CMD'] = self.CMD
        self.FSMSTATUS = RM_Register_MODEM_NS_FSMSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['FSMSTATUS'] = self.FSMSTATUS
        self.STATUS2 = RM_Register_MODEM_NS_STATUS2(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS2'] = self.STATUS2
        self.STATUS3 = RM_Register_MODEM_NS_STATUS3(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS3'] = self.STATUS3
        self.IRCAL = RM_Register_MODEM_NS_IRCAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['IRCAL'] = self.IRCAL
        self.IRCALCOEF = RM_Register_MODEM_NS_IRCALCOEF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IRCALCOEF'] = self.IRCALCOEF
        self.BLEIQDSA = RM_Register_MODEM_NS_BLEIQDSA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BLEIQDSA'] = self.BLEIQDSA
        self.BLEIQDSAEXT1 = RM_Register_MODEM_NS_BLEIQDSAEXT1(self.zz_rmio, self.zz_label)
        self.zz_rdict['BLEIQDSAEXT1'] = self.BLEIQDSAEXT1
        self.SYNCPROPERTIES = RM_Register_MODEM_NS_SYNCPROPERTIES(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNCPROPERTIES'] = self.SYNCPROPERTIES
        self.DIGIGAINCTRL = RM_Register_MODEM_NS_DIGIGAINCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIGIGAINCTRL'] = self.DIGIGAINCTRL
        self.PRSCTRL = RM_Register_MODEM_NS_PRSCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PRSCTRL'] = self.PRSCTRL
        self.PADEBUG = RM_Register_MODEM_NS_PADEBUG(self.zz_rmio, self.zz_label)
        self.zz_rdict['PADEBUG'] = self.PADEBUG
        self.REALTIMCFE = RM_Register_MODEM_NS_REALTIMCFE(self.zz_rmio, self.zz_label)
        self.zz_rdict['REALTIMCFE'] = self.REALTIMCFE
        self.SEQIF = RM_Register_MODEM_NS_SEQIF(self.zz_rmio, self.zz_label)
        self.zz_rdict['SEQIF'] = self.SEQIF
        self.SEQIEN = RM_Register_MODEM_NS_SEQIEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['SEQIEN'] = self.SEQIEN
        self.ETSCTRL = RM_Register_MODEM_NS_ETSCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['ETSCTRL'] = self.ETSCTRL
        self.ANTSWCTRL = RM_Register_MODEM_NS_ANTSWCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTSWCTRL'] = self.ANTSWCTRL
        self.ANTSWSTART = RM_Register_MODEM_NS_ANTSWSTART(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTSWSTART'] = self.ANTSWSTART
        self.ANTSWEND = RM_Register_MODEM_NS_ANTSWEND(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTSWEND'] = self.ANTSWEND
        self.TRECPMPATT = RM_Register_MODEM_NS_TRECPMPATT(self.zz_rmio, self.zz_label)
        self.zz_rdict['TRECPMPATT'] = self.TRECPMPATT
        self.TRECPMDET = RM_Register_MODEM_NS_TRECPMDET(self.zz_rmio, self.zz_label)
        self.zz_rdict['TRECPMDET'] = self.TRECPMDET
        self.CFGANTPATT = RM_Register_MODEM_NS_CFGANTPATT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CFGANTPATT'] = self.CFGANTPATT
        self.ETSTIM = RM_Register_MODEM_NS_ETSTIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['ETSTIM'] = self.ETSTIM
        self.ANTSWCTRL1 = RM_Register_MODEM_NS_ANTSWCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTSWCTRL1'] = self.ANTSWCTRL1
        self.COCURRMODE = RM_Register_MODEM_NS_COCURRMODE(self.zz_rmio, self.zz_label)
        self.zz_rdict['COCURRMODE'] = self.COCURRMODE
        self.ANTDIVCTRL = RM_Register_MODEM_NS_ANTDIVCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTDIVCTRL'] = self.ANTDIVCTRL
        self.BLEIQDSAEXT2 = RM_Register_MODEM_NS_BLEIQDSAEXT2(self.zz_rmio, self.zz_label)
        self.zz_rdict['BLEIQDSAEXT2'] = self.BLEIQDSAEXT2
        self.SPARE = RM_Register_MODEM_NS_SPARE(self.zz_rmio, self.zz_label)
        self.zz_rdict['SPARE'] = self.SPARE
        self.IRCALCOEFWR0 = RM_Register_MODEM_NS_IRCALCOEFWR0(self.zz_rmio, self.zz_label)
        self.zz_rdict['IRCALCOEFWR0'] = self.IRCALCOEFWR0
        self.IRCALCOEFWR1 = RM_Register_MODEM_NS_IRCALCOEFWR1(self.zz_rmio, self.zz_label)
        self.zz_rdict['IRCALCOEFWR1'] = self.IRCALCOEFWR1
        self.__dict__['zz_frozen'] = True