
# -*- coding: utf-8 -*-

__all__ = [ 'RM_Peripheral_MODEM_S' ]

from . static import Base_RM_Peripheral
from . MODEM_S_register import *

class RM_Peripheral_MODEM_S(Base_RM_Peripheral):
    def __init__(self, rmio, label):
        self.__dict__['zz_frozen'] = False
        super(RM_Peripheral_MODEM_S, self).__init__(rmio, label,
            0xA8014000, 'MODEM_S',
            u"",
            [])
        self.IPVERSION = RM_Register_MODEM_S_IPVERSION(self.zz_rmio, self.zz_label)
        self.zz_rdict['IPVERSION'] = self.IPVERSION
        self.EN = RM_Register_MODEM_S_EN(self.zz_rmio, self.zz_label)
        self.zz_rdict['EN'] = self.EN
        self.IF = RM_Register_MODEM_S_IF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IF'] = self.IF
        self.IEN = RM_Register_MODEM_S_IEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['IEN'] = self.IEN
        self.SEQIF = RM_Register_MODEM_S_SEQIF(self.zz_rmio, self.zz_label)
        self.zz_rdict['SEQIF'] = self.SEQIF
        self.SEQIEN = RM_Register_MODEM_S_SEQIEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['SEQIEN'] = self.SEQIEN
        self.STATUS = RM_Register_MODEM_S_STATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS'] = self.STATUS
        self.STATUS2 = RM_Register_MODEM_S_STATUS2(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS2'] = self.STATUS2
        self.STATUS3 = RM_Register_MODEM_S_STATUS3(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS3'] = self.STATUS3
        self.STATUS4 = RM_Register_MODEM_S_STATUS4(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS4'] = self.STATUS4
        self.STATUS5 = RM_Register_MODEM_S_STATUS5(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS5'] = self.STATUS5
        self.STATUS6 = RM_Register_MODEM_S_STATUS6(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS6'] = self.STATUS6
        self.STATUS7 = RM_Register_MODEM_S_STATUS7(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS7'] = self.STATUS7
        self.TIMDETSTATUS = RM_Register_MODEM_S_TIMDETSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['TIMDETSTATUS'] = self.TIMDETSTATUS
        self.FSMSTATUS = RM_Register_MODEM_S_FSMSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['FSMSTATUS'] = self.FSMSTATUS
        self.FREQOFFEST = RM_Register_MODEM_S_FREQOFFEST(self.zz_rmio, self.zz_label)
        self.zz_rdict['FREQOFFEST'] = self.FREQOFFEST
        self.AFCADJRX = RM_Register_MODEM_S_AFCADJRX(self.zz_rmio, self.zz_label)
        self.zz_rdict['AFCADJRX'] = self.AFCADJRX
        self.AFCADJTX = RM_Register_MODEM_S_AFCADJTX(self.zz_rmio, self.zz_label)
        self.zz_rdict['AFCADJTX'] = self.AFCADJTX
        self.CTRL0 = RM_Register_MODEM_S_CTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL0'] = self.CTRL0
        self.CTRL1 = RM_Register_MODEM_S_CTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL1'] = self.CTRL1
        self.CTRL2 = RM_Register_MODEM_S_CTRL2(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL2'] = self.CTRL2
        self.CTRL3 = RM_Register_MODEM_S_CTRL3(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL3'] = self.CTRL3
        self.CTRL4 = RM_Register_MODEM_S_CTRL4(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL4'] = self.CTRL4
        self.CTRL5 = RM_Register_MODEM_S_CTRL5(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL5'] = self.CTRL5
        self.CTRL6 = RM_Register_MODEM_S_CTRL6(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL6'] = self.CTRL6
        self.TXBR = RM_Register_MODEM_S_TXBR(self.zz_rmio, self.zz_label)
        self.zz_rdict['TXBR'] = self.TXBR
        self.RXBR = RM_Register_MODEM_S_RXBR(self.zz_rmio, self.zz_label)
        self.zz_rdict['RXBR'] = self.RXBR
        self.PRE = RM_Register_MODEM_S_PRE(self.zz_rmio, self.zz_label)
        self.zz_rdict['PRE'] = self.PRE
        self.SYNC0 = RM_Register_MODEM_S_SYNC0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNC0'] = self.SYNC0
        self.SYNC1 = RM_Register_MODEM_S_SYNC1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNC1'] = self.SYNC1
        self.TIMING = RM_Register_MODEM_S_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['TIMING'] = self.TIMING
        self.DSSS0 = RM_Register_MODEM_S_DSSS0(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSSS0'] = self.DSSS0
        self.MODINDEX = RM_Register_MODEM_S_MODINDEX(self.zz_rmio, self.zz_label)
        self.zz_rdict['MODINDEX'] = self.MODINDEX
        self.AFC = RM_Register_MODEM_S_AFC(self.zz_rmio, self.zz_label)
        self.zz_rdict['AFC'] = self.AFC
        self.AFCADJLIM = RM_Register_MODEM_S_AFCADJLIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['AFCADJLIM'] = self.AFCADJLIM
        self.SHAPING0 = RM_Register_MODEM_S_SHAPING0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING0'] = self.SHAPING0
        self.SHAPING1 = RM_Register_MODEM_S_SHAPING1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING1'] = self.SHAPING1
        self.SHAPING2 = RM_Register_MODEM_S_SHAPING2(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING2'] = self.SHAPING2
        self.SHAPING3 = RM_Register_MODEM_S_SHAPING3(self.zz_rmio, self.zz_label)
        self.zz_rdict['SHAPING3'] = self.SHAPING3
        self.RAMPCTRL = RM_Register_MODEM_S_RAMPCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['RAMPCTRL'] = self.RAMPCTRL
        self.RAMPLEV = RM_Register_MODEM_S_RAMPLEV(self.zz_rmio, self.zz_label)
        self.zz_rdict['RAMPLEV'] = self.RAMPLEV
        self.ANARAMPCTRL = RM_Register_MODEM_S_ANARAMPCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANARAMPCTRL'] = self.ANARAMPCTRL
        self.INTAFC = RM_Register_MODEM_S_INTAFC(self.zz_rmio, self.zz_label)
        self.zz_rdict['INTAFC'] = self.INTAFC
        self.DSATHD0 = RM_Register_MODEM_S_DSATHD0(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD0'] = self.DSATHD0
        self.DSATHD1 = RM_Register_MODEM_S_DSATHD1(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD1'] = self.DSATHD1
        self.DSATHD2 = RM_Register_MODEM_S_DSATHD2(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD2'] = self.DSATHD2
        self.DSATHD3 = RM_Register_MODEM_S_DSATHD3(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD3'] = self.DSATHD3
        self.DSATHD4 = RM_Register_MODEM_S_DSATHD4(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSATHD4'] = self.DSATHD4
        self.DSACTRL = RM_Register_MODEM_S_DSACTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSACTRL'] = self.DSACTRL
        self.VITERBIDEMOD = RM_Register_MODEM_S_VITERBIDEMOD(self.zz_rmio, self.zz_label)
        self.zz_rdict['VITERBIDEMOD'] = self.VITERBIDEMOD
        self.VTCORRCFG0 = RM_Register_MODEM_S_VTCORRCFG0(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTCORRCFG0'] = self.VTCORRCFG0
        self.VTCORRCFG1 = RM_Register_MODEM_S_VTCORRCFG1(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTCORRCFG1'] = self.VTCORRCFG1
        self.VTTRACK = RM_Register_MODEM_S_VTTRACK(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTTRACK'] = self.VTTRACK
        self.VTBLETIMING = RM_Register_MODEM_S_VTBLETIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['VTBLETIMING'] = self.VTBLETIMING
        self.BREST = RM_Register_MODEM_S_BREST(self.zz_rmio, self.zz_label)
        self.zz_rdict['BREST'] = self.BREST
        self.AUTOCG = RM_Register_MODEM_S_AUTOCG(self.zz_rmio, self.zz_label)
        self.zz_rdict['AUTOCG'] = self.AUTOCG
        self.CGCLKSTOP = RM_Register_MODEM_S_CGCLKSTOP(self.zz_rmio, self.zz_label)
        self.zz_rdict['CGCLKSTOP'] = self.CGCLKSTOP
        self.POE = RM_Register_MODEM_S_POE(self.zz_rmio, self.zz_label)
        self.zz_rdict['POE'] = self.POE
        self.DIRECTMODE = RM_Register_MODEM_S_DIRECTMODE(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIRECTMODE'] = self.DIRECTMODE
        self.LONGRANGE = RM_Register_MODEM_S_LONGRANGE(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE'] = self.LONGRANGE
        self.LONGRANGE1 = RM_Register_MODEM_S_LONGRANGE1(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE1'] = self.LONGRANGE1
        self.LONGRANGE2 = RM_Register_MODEM_S_LONGRANGE2(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE2'] = self.LONGRANGE2
        self.LONGRANGE3 = RM_Register_MODEM_S_LONGRANGE3(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE3'] = self.LONGRANGE3
        self.LONGRANGE4 = RM_Register_MODEM_S_LONGRANGE4(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE4'] = self.LONGRANGE4
        self.LONGRANGE5 = RM_Register_MODEM_S_LONGRANGE5(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE5'] = self.LONGRANGE5
        self.LONGRANGE6 = RM_Register_MODEM_S_LONGRANGE6(self.zz_rmio, self.zz_label)
        self.zz_rdict['LONGRANGE6'] = self.LONGRANGE6
        self.LRFRC = RM_Register_MODEM_S_LRFRC(self.zz_rmio, self.zz_label)
        self.zz_rdict['LRFRC'] = self.LRFRC
        self.COH0 = RM_Register_MODEM_S_COH0(self.zz_rmio, self.zz_label)
        self.zz_rdict['COH0'] = self.COH0
        self.COH1 = RM_Register_MODEM_S_COH1(self.zz_rmio, self.zz_label)
        self.zz_rdict['COH1'] = self.COH1
        self.COH2 = RM_Register_MODEM_S_COH2(self.zz_rmio, self.zz_label)
        self.zz_rdict['COH2'] = self.COH2
        self.COH3 = RM_Register_MODEM_S_COH3(self.zz_rmio, self.zz_label)
        self.zz_rdict['COH3'] = self.COH3
        self.CMD = RM_Register_MODEM_S_CMD(self.zz_rmio, self.zz_label)
        self.zz_rdict['CMD'] = self.CMD
        self.SYNCPROPERTIES = RM_Register_MODEM_S_SYNCPROPERTIES(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNCPROPERTIES'] = self.SYNCPROPERTIES
        self.PRSCTRL = RM_Register_MODEM_S_PRSCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PRSCTRL'] = self.PRSCTRL
        self.PADEBUG = RM_Register_MODEM_S_PADEBUG(self.zz_rmio, self.zz_label)
        self.zz_rdict['PADEBUG'] = self.PADEBUG
        self.REALTIMCFE = RM_Register_MODEM_S_REALTIMCFE(self.zz_rmio, self.zz_label)
        self.zz_rdict['REALTIMCFE'] = self.REALTIMCFE
        self.ETSCTRL = RM_Register_MODEM_S_ETSCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['ETSCTRL'] = self.ETSCTRL
        self.ETSTIM = RM_Register_MODEM_S_ETSTIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['ETSTIM'] = self.ETSTIM
        self.ANTSWCTRL = RM_Register_MODEM_S_ANTSWCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTSWCTRL'] = self.ANTSWCTRL
        self.ANTSWCTRL1 = RM_Register_MODEM_S_ANTSWCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTSWCTRL1'] = self.ANTSWCTRL1
        self.ANTSWSTART = RM_Register_MODEM_S_ANTSWSTART(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTSWSTART'] = self.ANTSWSTART
        self.ANTSWEND = RM_Register_MODEM_S_ANTSWEND(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTSWEND'] = self.ANTSWEND
        self.TRECPMPATT = RM_Register_MODEM_S_TRECPMPATT(self.zz_rmio, self.zz_label)
        self.zz_rdict['TRECPMPATT'] = self.TRECPMPATT
        self.TRECPMDET = RM_Register_MODEM_S_TRECPMDET(self.zz_rmio, self.zz_label)
        self.zz_rdict['TRECPMDET'] = self.TRECPMDET
        self.TRECSCFG = RM_Register_MODEM_S_TRECSCFG(self.zz_rmio, self.zz_label)
        self.zz_rdict['TRECSCFG'] = self.TRECSCFG
        self.CFGANTPATT = RM_Register_MODEM_S_CFGANTPATT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CFGANTPATT'] = self.CFGANTPATT
        self.COCURRMODE = RM_Register_MODEM_S_COCURRMODE(self.zz_rmio, self.zz_label)
        self.zz_rdict['COCURRMODE'] = self.COCURRMODE
        self.FRMSCHTIME = RM_Register_MODEM_S_FRMSCHTIME(self.zz_rmio, self.zz_label)
        self.zz_rdict['FRMSCHTIME'] = self.FRMSCHTIME
        self.PREFILTCOEFF = RM_Register_MODEM_S_PREFILTCOEFF(self.zz_rmio, self.zz_label)
        self.zz_rdict['PREFILTCOEFF'] = self.PREFILTCOEFF
        self.RXRESTART = RM_Register_MODEM_S_RXRESTART(self.zz_rmio, self.zz_label)
        self.zz_rdict['RXRESTART'] = self.RXRESTART
        self.SQ = RM_Register_MODEM_S_SQ(self.zz_rmio, self.zz_label)
        self.zz_rdict['SQ'] = self.SQ
        self.SQEXT = RM_Register_MODEM_S_SQEXT(self.zz_rmio, self.zz_label)
        self.zz_rdict['SQEXT'] = self.SQEXT
        self.SQI = RM_Register_MODEM_S_SQI(self.zz_rmio, self.zz_label)
        self.zz_rdict['SQI'] = self.SQI
        self.ANTDIVCTRL = RM_Register_MODEM_S_ANTDIVCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTDIVCTRL'] = self.ANTDIVCTRL
        self.ANTDIVFW = RM_Register_MODEM_S_ANTDIVFW(self.zz_rmio, self.zz_label)
        self.zz_rdict['ANTDIVFW'] = self.ANTDIVFW
        self.PHDMODANTDIV = RM_Register_MODEM_S_PHDMODANTDIV(self.zz_rmio, self.zz_label)
        self.zz_rdict['PHDMODANTDIV'] = self.PHDMODANTDIV
        self.PHANTDECSION = RM_Register_MODEM_S_PHANTDECSION(self.zz_rmio, self.zz_label)
        self.zz_rdict['PHANTDECSION'] = self.PHANTDECSION
        self.PHDMODCTRL = RM_Register_MODEM_S_PHDMODCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PHDMODCTRL'] = self.PHDMODCTRL
        self.SICTRL0 = RM_Register_MODEM_S_SICTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['SICTRL0'] = self.SICTRL0
        self.SICTRL1 = RM_Register_MODEM_S_SICTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['SICTRL1'] = self.SICTRL1
        self.SISTATUS = RM_Register_MODEM_S_SISTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['SISTATUS'] = self.SISTATUS
        self.CFGANTPATTEXT = RM_Register_MODEM_S_CFGANTPATTEXT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CFGANTPATTEXT'] = self.CFGANTPATTEXT
        self.SICTRL2 = RM_Register_MODEM_S_SICTRL2(self.zz_rmio, self.zz_label)
        self.zz_rdict['SICTRL2'] = self.SICTRL2
        self.CHFSWCTRL = RM_Register_MODEM_S_CHFSWCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHFSWCTRL'] = self.CHFSWCTRL
        self.HADMCTRL0 = RM_Register_MODEM_S_HADMCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMCTRL0'] = self.HADMCTRL0
        self.HADMCTRL1 = RM_Register_MODEM_S_HADMCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMCTRL1'] = self.HADMCTRL1
        self.HADMSTATUS0 = RM_Register_MODEM_S_HADMSTATUS0(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS0'] = self.HADMSTATUS0
        self.HADMSTATUS1 = RM_Register_MODEM_S_HADMSTATUS1(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS1'] = self.HADMSTATUS1
        self.HADMSTATUS2 = RM_Register_MODEM_S_HADMSTATUS2(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS2'] = self.HADMSTATUS2
        self.HADMSTATUS3 = RM_Register_MODEM_S_HADMSTATUS3(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS3'] = self.HADMSTATUS3
        self.HADMSTATUS4 = RM_Register_MODEM_S_HADMSTATUS4(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS4'] = self.HADMSTATUS4
        self.HADMSTATUS5 = RM_Register_MODEM_S_HADMSTATUS5(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS5'] = self.HADMSTATUS5
        self.HADMSTATUS6 = RM_Register_MODEM_S_HADMSTATUS6(self.zz_rmio, self.zz_label)
        self.zz_rdict['HADMSTATUS6'] = self.HADMSTATUS6
        self.TXCORR = RM_Register_MODEM_S_TXCORR(self.zz_rmio, self.zz_label)
        self.zz_rdict['TXCORR'] = self.TXCORR
        self.TXMISC = RM_Register_MODEM_S_TXMISC(self.zz_rmio, self.zz_label)
        self.zz_rdict['TXMISC'] = self.TXMISC
        self.SPARE = RM_Register_MODEM_S_SPARE(self.zz_rmio, self.zz_label)
        self.zz_rdict['SPARE'] = self.SPARE
        self.__dict__['zz_frozen'] = True